insight.worker.execution.environment.MOSEL_RESTR=0
insight.worker.execution.environment.PYTHON_EXE=/home/worker/.conda/envs/${MINICONDA_ENV}/bin/python
insight.worker.execution.environment.PATH=${PATH}
