insight.server.visualization.mirror.username=insight
insight.server.visualization.mirror.password=${mirror_db_password}
insight.server.visualization.mirror.url=jdbc:mariadb://mirror-db:3306/mirror_master