insight.server.persistence.store=mysql
insight.server.persistence.mysql.enforce-validation=false
insight.server.persistence.mysql.url=jdbc:mysql://db:3306/insight
insight.server.persistence.mysql.password=${db_password}