insight.server.visualization.tableau.url=${TABLEAU_URL}
insight.server.visualization.tableau.system-user=${TABLEAU_USER}
insight.server.visualization.tableau.system-password=${tableau_password}
insight.server.visualization.tableau.site-id=${TABLEAU_SITE_ID}
insight.server.visualization.tableau.mirror.host=${MIRROR_HOST}
insight.server.visualization.tableau.mirror.port=${MIRROR_PORT}