name: example-environment
channels:
  - fico-xpress
  - conda-forge
  # Add intel channel, needed for some dependencies
  - https://software.repos.intel.com/python/conda/
dependencies:
  - python~=3.12
  - xpressinsight=1.16.0
  - xpress=9.8.0
  - debugpy~=1.8
  - polars-lts-cpu # needed for Python models that use Polars
