services:
    init:
      image: docker.io/amazoncorretto:17-al2023
      environment:
        - ENABLE_SSL=${ENABLE_SSL}
      volumes:
        - ./scripts/init.sh:/scripts/init.sh
        - public-certificates:/public-certificates
        - ../server-config:/server/config
      secrets:
          - ssl_keystore_password
      command: sh /scripts/init.sh
      restart: "no"

    server:
        build:
            context: ..
            dockerfile: dockerfile/server.Dockerfile
            no_cache: true
            args:
                IMAGE_SERVER: ${IMAGE_SERVER}${INSIGHT_VERSION:+:${INSIGHT_VERSION}}
        ports:
            # SERVER_PORT is defined in the .env file (default 8080)
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
            - SERVER_HOSTNAME=${SERVER_HOSTNAME}
            - SERVER_PORT=${SERVER_PORT}
            - ENABLE_SSL=${ENABLE_SSL}
            - SERVER_PROTOCOL=${SERVER_PROTOCOL}
            - INSIGHT_CONFIGURATION_KEY=${INSIGHT_CONFIGURATION_KEY}
        volumes:
            # server-config mounted onto server/config in the container
            - ../server-config:/server/config
            # When it starts, the server generates a public certificate visible to the worker
            - public-certificates:/server/public-certificates
            # Where to store the server logs.
            - ${LOGS_VOLUME:-../logs}:/server/logs
        secrets:
            - ssl_keystore_password
        healthcheck:
            test: curl --insecure -f ${SERVER_PROTOCOL:-http}://localhost:${SERVER_PORT}/insightservices/rest/ready || exit 1
            retries: 10
            interval: 15s
            timeout: 10s
        depends_on:
          init:
            condition: service_completed_successfully

    worker:
        depends_on:
            server:
                condition: service_healthy
        build:
            context: ..
            dockerfile: dockerfile/worker.Dockerfile
            no_cache: true
            args:
                IMAGE_WORKER: ${IMAGE_WORKER}${INSIGHT_VERSION:+:${INSIGHT_VERSION}}
        environment:
            - SERVER_PORT=${SERVER_PORT}
            - ENABLE_SSL=${ENABLE_SSL}
            - SERVER_PROTOCOL=${SERVER_PROTOCOL}
            - INSIGHT_CONFIGURATION_KEY=${INSIGHT_CONFIGURATION_KEY}
        volumes:
            # worker-config mounted onto worker/config in the container
            - ../worker-config:/worker/config
            # Add the server's public certificate
            - public-certificates:/worker/public-certificates
            # Where to store the worker logs. Uncomment the line below if needing to save the logs to files
            - ${LOGS_VOLUME:-../logs}:/worker/logs
            # to override the license
            - ../xpress-license:/xpress-license
        secrets:
            - ssl_keystore_password
        healthcheck:
            test: curl --insecure -f ${SERVER_PROTOCOL:-http}://localhost:${SERVER_PORT}/worker/rest/alive || exit 1
            retries: 10
            interval: 15s
            timeout: 10s
    workbench:
        build:
            context: ..
            dockerfile: dockerfile/workbench.Dockerfile
            no_cache: true
            args:
                IMAGE_WORKBENCH: ${IMAGE_WORKBENCH}${INSIGHT_VERSION:+:${INSIGHT_VERSION}}
        ports:
            - "127.0.0.1:${WORKBENCH_EXTERNAL_PORT}:8080"
        volumes:
            # where to store the user data (default to the internal docker volume)
            - ${WORKBENCH_DATA_VOLUME:-workbench-data}:/workbench-data

            # configuration for Workbench
            - ../workbench-config:/workbench-config

            # where to store the insight servers credentials
            - workbench-server-credentials:/workbench-server-credentials

            # where to store the logs
            - workbench-logs:/workbench-logs

            # So Workbench can trust self-signed certificates from server
            - public-certificates:/public-certificates

            # to override the license
            - ../xpress-license:/xp-license

        environment:
            - SERVER_PORT=${SERVER_PORT}
            - ENABLE_SSL=${ENABLE_SSL}
            - WORKBENCH_LOGGING=${WORKBENCH_LOGGING:-}
            - MOSEL_RUNNER_LOGGING=${MOSEL_RUNNER_LOGGING:-}
            - GRPC_TRACE=${GRPC_TRACE:-}
            - GRPC_VERBOSITY=${GRPC_VERBOSITY:-}
            - WORKBENCH_EXTRA_CA_CERT_FILES=${WORKBENCH_EXTRA_CA_CERT_FILES:-}
        depends_on:
          init:
            condition: service_completed_successfully

secrets:
    ssl_keystore_password:
        file: ../secrets/ssl_keystore_password.txt
volumes:
    public-certificates:
    workbench-data:
    workbench-server-credentials:
    workbench-logs:
