services:
    server:
        platform: linux/amd64
        build:
            dockerfile: ../server.Dockerfile
            no_cache: true
            args:
              IMAGE_SERVER: ${IMAGE_SERVER}${INSIGHT_VERSION:+:${INSIGHT_VERSION}}
        ports:
            # SERVER_EXTERNAL_PORT is defined in the .env file (default 8080)
            - "${SERVER_EXTERNAL_PORT}:8080"
        environment:
            - SERVER_EXTERNAL_PORT=${SERVER_EXTERNAL_PORT}
        volumes:
            # server-config mounted onto server/config in the container
            - ./server-config:/server/config
            # You can see the repo and silo are in the volume 'insight-local-filesystem_data'
            - data:/data
            # When it starts, the server generates a public certificate visible to the worker
            - public-certificates:/server/public-certificates
            # Where to store the server logs. Uncomment the line below if needing to save the logs to files
            #- ./logs:/server/logs
        healthcheck:
            test: curl http://server:8080/insightservices/rest/ready || exit 1
    worker:
        depends_on:
            server:
                condition: service_healthy
        platform: linux/amd64
        build:
            dockerfile: ../worker.Dockerfile
            no_cache: true
            args:
              IMAGE_WORKER: ${IMAGE_WORKER}${INSIGHT_VERSION:+:${INSIGHT_VERSION}}
        volumes:
            # worker-config mounted onto worker/config in the container
            - ./worker-config:/worker/config
            # Add the server's public certificate
            - public-certificates:/worker/public-certificates
            # Where to store the worker logs. Uncomment the line below if needing to save the logs to files
            #- ./logs:/worker/logs
        healthcheck:
            test: curl http://worker:8080/rest/alive || exit 1

volumes:
    data:
    public-certificates: